### ISSUE TITLE
Feature request: Option to enable hitting creeper with torch to ignite them

### ISSUE THREAD

**Issue by 3ncanis** [Nyphet/torch-hit#22] opened 2024-04-09 21:42 UTC
Basically I think it would be a cool feature where hitting a creeper with a torch causes it to ignite similar to how right clicking on them with a flint and steel works.

**Comment by Crystal-Spider** [comment] 2024-04-10 15:53
Duplicate of #7 

Does fire aspect set creepers on fire?

**Closed as completed by Crystal-Spider** 2024-04-10 15:53 UTC
Labels: duplicate, enhancement, wontfix

**Comment by 3ncanis** [comment] 2024-04-11 07:58
Yes?

**Comment by Crystal-Spider** [comment] 2024-04-11 08:24
Sorry, I meant, does fire aspect ignite creepers and make them explode? Or does it only set them on fire?  
Torches are meant to be an early game alternative to fire aspect, or a way to get a combat advantage by not using the shield in caves, so the behavior should be consistent with that.

**Comment by 3ncanis** [comment] 2024-04-11 08:54
Understandable, just thought it would be a fun feature you could toggle on, disabled by default. But I do realize it would pretty much make flint and steel useless
